; INI Scenario Format - used for:
;   - Default Scenario Settings 
;   - Scenario Import/Export:
;
; Data will appear in the scenario manager based on the order it is 
; included in this file
;
; Section Headers can be:
; ----------------------
; [Info] --> Name, Input, Output
; [Input.Key] --> See below
; [<Type>.<STAGE>.Key]  -->See below
;    - Type can be any of: Input, Output, Table, Param, DbTable
;    - Stage needs to match the model structure
;
; Available Parameters for sections other than [Info]:
; ---------------------
; Value = Filename or Parameter value (required)
; Desc = Description of item
; For Input/Output only:
;   Choice = "Optional" File is optional if this line is included
;
; Shorthand for Param, Table
; [Param.<Stage>]
; Key = Value | Desc
;
; Shorthand for Output:
; [Output.<Stage>]
; Key = Value | Desc | [Optional/Partial]
; --> If the keyword Optional is included, the file will be optional
; --> If the keyword Partial is included, at least one template file is required (not all)
;
; WARNING - Shorthand has not been enabled for Input!

[Info]
Name = New Scenario   ;Scenario Name
Input Directory = C:\SEMCOG_ActSim\Model_Runs\New_Scenario\Input\ ;TODO - not currently used
Output Directory = C:\SEMCOG_ActSim\Model_Runs\New_Scenario\Output\ ;TODO - not currently used
[Input.Highway DB]
Value = Network\HwyLA25.dbd
Desc = Roadway Geographic File
[Input.AllStreets DB]
Value = Network\V17_SEMCOG_tRoad1.dbd
Desc = All Streets Network File
[Input.Turn_Pena]
Value = Network\TURNPRO25.BIN
Desc = Trun Penalty file
[Input.Route System]
Value = Network\RtLA25.rts
Desc = Transit Route System
[Input.Zonal Fare]
Value = Network\Zone_Fare.mtx
Desc = Zone to zone transit fare matrix
[Input.Speed Capacity Table]
Value = Network\spdcaplu_abm.bin
Desc = Speed and Capacity lookup table
[Input.Crit_Query]
Value = Network\MyCriticalLinks.qry
Desc = Select link and/or zone query definition
Choice = Optional
[Input.TAZ]
Value = Zonal_Data\Zones10_2899.dbd
Desc = Traffic Analysis Zone geographic file
[Input.MAZ]
Value = Zonal_Data\SEMCOG_MAZ_V2.dbd
Desc = MAZ geographic file
[Input.Land Use Data]
Value = SE_Data\2025_maz_zonal_data.csv
[Input.Other Zonal Data]
Value = SE_Data\2025_maz_zonal_data_other.csv
Desc = Landuse Data File
[Input.Synthetic Households File]
Value = SE_Data\2025_households_maz.csv
Desc = Synthetic Households file for ActivitySim
[Input.Synthetic Persons File]
Value = SE_Data\2025_persons_maz.csv
Desc = Synthetic Person file for ActivitySim
[Input.Mode Table]
Value = Params\ModeTable.bin
Desc = Transit mode table
[Input.Mode Transfer Table]
Value = Params\ModeXferTable.bin
Desc = Transit mode transfer cost table
[Input.External Params]
Value = Params\ExternalParams.bin
Desc = External trip calibration parameters
[Input.Person IEEI file]
Value = SE_Data\Person_IEEI_2025.bin
Desc = EI/IE trip file
[Input.Person EE file]
Value = SE_Data\Person_EE_2025.csv
Desc = EE trip file
[Input.Airport data]
Value = SE_Data\Airport_STrip_2025.bin
Desc = EI/IE trip file
[Input.Transit Para Table]
Value = Params\transitPara_abm.bin
Desc = Transit network parameter table
[Input.Term Time Lookup]
Value = Params\TTLookup.bin
Desc = Terminal Time Lookup Table
[Input.Count Table]
Value = Network\CountTable.bin
Desc = Traffic count table for use in model validation reporting and maps
Choice = Optional
[Input.Process landuse]
Value = ..\..\..\ABM\Scripts\process_landuse.bat
Desc = Batch file to run Proc land use
[Input.ActivitySim Preprocessing Batch File]
Value = ..\..\..\ABM\Scripts\run_semcog_abm_skimprep.bat
Desc = Batch file to run ActivitySim Preprocessing scripts, including pooling together skims and creating 2-zone specific skim tables
[Input.ActivitySim Batch File]
Value = ..\..\..\ABM\Scripts\run_semcog_abm_activitysim.bat
Desc = Batch file to run ActivitySim
[Input.ActivitySim Postprocessing Batch File]
Value = ..\..\..\ABM\Scripts\run_semcog_abm_postprocessing.bat
Desc = Batch file to run ActivitySim Postprocessing script
[Input.ActivitySim Visualizer Batch File]
Value = ..\..\..\ABM\Scripts\run_semcog_abm_visualizer.bat
Desc = Batch file to run ActivitySim Visualizer
[Input.Buffer TAZ Data]
Value = SE_Data\CVM_TAZ_SE_Buffer_2025.csv
Desc = TAZ data for the buffer region used in the CVM
[Input.Facilities Data]
Value = SE_Data\CVM_Facilities_RTP50.csv
Desc = Freight activity centers facilties used in the CVM
[Input.CVM IEEI Trucks]
Value = SE_Data\CVM_IEEI_Region_2025.csv
Desc = Daily IE and EI Trucks by External Region, used in the CVM
[Input.CVM EE Trucks]
Value = SE_Data\CVM_EE_Region_2025.csv
Desc = Daily EE Trucks by External Region, used in the CVM
[Input.CVM Externals]
Value = SE_Data\CVM_Externals_2025.csv
Desc = Active external stations and allocation factors, used in the CVM
[Input.Base Year Firms]
Value = SE_Data\BaseFirms.Rdata
Desc = Base Year Firm Synthesis Output Database (Rdata file) used in any non-base scenario in the CVM
Choice = Optional
[Input.CVM Static Trip Table]
Value = SE_Data\CV_Trip_Tables.omx
Desc = Static CVM Trip Table
Choice = Optional
[Input.CVM Batch File]
Value = ..\..\..\CVM\run_semcog_cvtm.bat
Desc = Batch file to run Commercial Vehicle Model
[Input.EJ Batch File]
Value = ..\..\..\ABM\Scripts\run_semcog_EJ.bat
Desc = Batch file to run EJ module

[Output.INI]
Network File = HNet\semcog_hwy.net | Network File
Transit Network = TNet\TransitNetwork_%PER_TRN%.tnw | Transit networks by period
Working Files = WorkingFiles\nodes_all.shp | Exported files
TAZ Land Use Data = WorkingFiles\land_use_taz.csv | Aggregated MAZ land use data to the TAZ level
Merged Land Use Data = ..\Input\SE_Data\land_use_ActivitySim.csv | Merged land use data (land use  + other zonal data) to be read by ActivitySim
[Output.SKM]
HwySkims = skims\%PER_HWY%_HwySkim.mtx | Highway Skims by Time Period
EAHwySkims = skims\EA_HwySkim.mtx | EA Highway Skims
AMHwySkims = skims\AM_HwySkim.mtx | AM Highway Skims
MDHwySkims = skims\MD_HwySkim.mtx | MD Highway Skims
PMHwySkims = skims\PM_HwySkim.mtx | PM Highway Skims
EVHwySkims = skims\EV_HwySkim.mtx | EV Highway Skims

PnR Access = TNet\%PER_TRN%_praccess_%TMODE%.mtx | Park and Ride Access Skims
PnR Egress = TNet\%PER_TRN%_pregress_%TMODE%.mtx | Park and Ride Egress Skims
Transit Skims = skims\%PER_TRN%_%AMODE%_%TMODE%_Skim.mtx | Transit Skim Files | Partial
Parking Matrix = skims\%PER_TRN%_%AMODE%_%TMODE%_Parking.mtx | Drive Access/Egress Parking Matrix (Not created for walk access modes) | Partial
[Output.EXT]
EXT Airport = EXTAirport\Airport_%PER_TRN%.mtx | External and Airport model outputs
[Output.ABM]
ABM trip matrices = ActivitySim\trips_%PER_TRN%.omx | ActivitySim passenger trip tables
ABM final tour file = ActivitySim\final_tours.csv | ActivitySim output tour table
ABM final trip file = ActivitySim\final_trips.csv | ActivitySim output trip table
ABM final joint tour file = ActivitySim\final_joint_tour_participants.csv | ActivitySim output joint tour table
ABM final accessibility file = ActivitySim\final_accessibility.csv | ActivitySim output accessibility table
ABM final land use file = ActivitySim\final_land_use.csv | ActivitySim output land use table
ABM final persons file = ActivitySim\final_persons.csv | ActivitySim output persons table
ABM final households file = ActivitySim\final_households.csv | ActivitySim output households table
[Output.CVM]
Firm Synthesis Database = CVM\1.Firms.Rdata | List of Firms from Frim Synthesis
Long Distance Database = CVM\2.LongDistanceTrips.Rdata | Long Distance Truck Trips
Commercial Vehicle Tours = CVM\3.CommercialVehicleTrips.Rdata | Commercial Vehicle Tours and Trips
CVM Trip Database = CVM\4.TripTables.Rdata | Commercial Vehicle Trip Database
CVM Trip Generation = CVM\CV_Trip_Generation_Summary.csv | Commercial Vehicle Trip Generation
CVM Dashboard = CVM_ReportDashboard.html | Commercial Vehicle | Optional

[Output.ASN]
OD Trip Tables = HAssign\OD_%PER_HWY%.omx | OD Trip Tables for Highway Assignment
Transit OD Trip Tables = TrnAssign\OD_TRN_%PER_TRN%.omx | OD Trip Tables for Transit Assignment

Highway Flows = HAssign\Flow_%PER_HWY%.bin | Highway Flow Files
Iteration Log = HAssign\IterLog%PER_HWY%.bin | Assignment iteration log
DY Highway Flows = HAssign\Flow_DY.bin | Highway Flow Files

Transit Flow Files = TrnAssign\Detail\TFLOW_%PER_TRN%_%AMODE%_%TMODE%.bin | Transit Flow Files
Transit Walk Files = TrnAssign\Detail\WFLOW_%PER_TRN%_%AMODE%_%TMODE%.bin | Transit Walk Flow Files
Transit Agg Files = TrnAssign\Detail\AFLOW_%PER_TRN%_%AMODE%_%TMODE%.bin | Transit Aggregated Flow Files
Transit OnOff Files = TrnAssign\Detail\ONOFF_%PER_TRN%_%AMODE%_%TMODE%.bin | Transit On/Off Files

Daily Transit Flow Files = TrnAssign\TFLOW_DY_All.bin | Transit Flow Files
Daily Transit Walk Files = TrnAssign\WFLOW_DY_All.bin | Transit Walk Flow Files
Daily Transit Agg Files = TrnAssign\AFLOW_DY_All.bin | Transit Aggregated Flow Files
Daily Transit OnOff Files = TrnAssign\ONOFF_DY_All.bin | Transit On/Off Files

SelectMatrix = HAssign\%PER_HWY%_SelectTrips.mtx | Select Trip Matrices | Optional
Feedback Report = HAssign\Feedback.txt | Speed Feedback Converge Report | Optional
[Output.RPT]
Summary Report = Summary.html | Model summary report | Optional
Detailed Summary Report = SummaryDetailed.html | Detailed model summary report | Optional
EJ Summary Report = EJ\EJSummary.html | EJ model summary report | Optional

[Param.INI]
Distance weight = 0.18 | Weight of distance for impedance calculation
Time weight = 0.30 | Weight of time for impedance calculation
Walk Speed = 2.8 | Walking speed in transit network and for non-motorized
Bike Speed = 12 | Bike speed for non-motorized 
Transit Band Width = 0.25 | Transit line band width (in miles)
ShortWalk = 5 | Short walk distance for transit skim processing
LongWalk = 10 | Long walk distance for transit skim processing
ShortWait = 7 | Short wait time for transit skim processing
[Param.SKM]
IntrazonalFactor = 0.5 | Intrazonal Multiplier
IntrazonalNeighbors = 4 | Number of Neighbors
[Param.ABM]
Anaconda_DIR = C:\SEMCOG_ActSim\VE_V1p3\.venv | Set the path to which the virtucal environment has been installed to
ENV_DIR = C:\SEMCOG_ActSim\VE_V1p3\.venv | Set the path to which the virtucal environment has been installed to
PYTHON_ENV_NAME = asim | Name of the ActivitySim python environment. There should be a folder with this name under ENV_DIR/env
BASE_IS_SURVEY = 1 | Set to 1 if the ABM visualizer should compare model output against survey
BASE_SCEN_DIR = C:\ | Used if the ABM visualizer base should not be survey. Set to the directory where the base scenario visualizer files are located (usually within Output/Activitysim/visualizer), otherwise leave as is.
[Param.ASN]
Air Occ 3p = 3.66 | Airport Occupancy rate for 3+category
Assign_EA_Iter = 100 | EA Assignment Iterations
Assign_AM_Iter = 100 | AM Assignment Iterations
Assign_MD_Iter = 100 | MD Assignment Iterations
Assign_PM_Iter = 100 | PM Assignment Iterations
Assign_EV_Iter = 100 | EV Assignment Iterations
Assign_EA_Conv = 0.001 | EA Assignment Convergence
Assign_AM_Conv = 0.001 | AM Assignment Convergence
Assign_MD_Conv = 0.001 | MD Assignment Convergence
Assign_PM_Conv = 0.001 | PM Assignment Convergence
Assign_EV_Conv = 0.001 | EV Assignment Convergence
RunFeedback = 0 | Enable or disable feedback
FeedbackIters = 5 | Maximum number of speed feedback iterations to run
FeedbackConv = 0 | Stop Feedback at an RMSE limit (0 to go to max iterations)
[Table.ASN]
Occ 3p  = {4.3,   3.66,  3.55,   3.64,   4.3,   3.48,  3.74} | Average occupancy for 3+ vehicles by trip purpose
HwySubPeriods = {{"AM", "PM"}, {"MD", "EV", "EA"}} | Periods for highway assignment, by peak and off-peak
HwyPeriods = {"EA", "AM", "MD", "PM", "EV"} | Periods for highway assignment
TrnSubPeriods = {{"AM", "PM"}, {"MD", "EV", "EA"}} | Periods for transit assignment, by peak and off-peak
TrnPeriods = {"EA", "AM", "MD", "PM", "EV"} | Periods for transit assignment
; PCE and Value of Time settings
sov_array = {1, 1} | SOV:  PCE and VOT
hov2_array = {1, 1} | HOV2: PCE and VOT
hov3_array = {1, 1} | HOV3: PCE and VOT
ltk_array = {1.0, 1} | LTK:  PCE and VOT
mtk_array = {1.89, 1} | MTK:  PCE and VOT
htk_array = {3.35, 1} | HTK:  PCE and VOT
[Param.CVM]
UseStaticCVMTrips = 0 | Set to 1 to use static CVMTrips, 0 to use run CVM (affects input file requirements)
BaseScenario = 1 | Set to 1 if this is the base scenario, 0 for all other alternative and future scenarios (affects the firm synthesis in the CVM)
R_DIR = pkgs\R-4.5.1\bin | path for the installation of RScript.exe used by the CVM and ABM Visualizer
R_LIBRARY = pkgs\library | path to the additional R packages used by the CVM and ABM Visualizer
PANDOC_DIR = pkgs\Pandoc | path for the installation of Pandoc used by the CVM and ABM Visualizer

